---

  - name: Install packages
    apt:
      pkg: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - git
      - emacs
      - firefox
      - tmux
      - htop
      - vim

  - name: Download google chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/google-chrome-stable_current_amd64.deb
  
  - name: Install google chrome
    apt: 
      deb: /tmp/google-chrome-stable_current_amd64.deb

  - name: Download dropbox
    get_url:
      url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
      dest: /tmp/dropbox.deb

  - name: Install dropbox
    apt: 
      deb: /tmp/dropbox.deb

  - name: Install awscli
    pip:
      name: awscli
      state: present

  - name: Download gitkraken
    get_url:
      url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
      dest: /tmp/gitkraken.deb

  - name: Install gitkraken
    apt: 
      deb: /tmp/gitkraken.deb


