---

  - name: Add gcloud SDK GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      keyring: /usr/share/keyrings/cloud.google.gpg

  - name: Add gcloud SDK repository
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main

  - name: Add Google Chrome repository
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

  - name: Add Visual Studio Code repository
    apt_repository:
      repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

  - name: Install packages
    apt:
      pkg: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - git
      - emacs
      - tmux
      - htop
      - vim
      - xclip
      - code
      - google-chrome-stable
      - google-cloud-sdk
      - golang
      - kubectl
      - kubectx

