---

  - name: Add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

  - name: Install docker
    apt:
      pkg: docker-ce
      state: present
      update_cache: yes

  - name: Add {{ user }} to Docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
    notify:
      - "start docker"

  - name: Install docker-compose
    pip:
      name: docker-compose
      state: present