---

  - include: upgrade_os.yml
  - include: install_common_packages.yml
  - include: setup_user.yml
  - include: configure_bash.yml
  - include: install_docker.yml
  - include: install_php.yml
  - include: reboot.yml
